"""Builds walkthrough_colab.ipynb: fully standalone (library inlined, data fetched from GitHub). Run: python make_colab_notebook.py"""
import nbformat as nbf
LIB = open("uma_manifold.py", encoding="utf-8").read()
RAW = "https://raw.githubusercontent.com/PranavViswanath/manifold-alchemy/main/"
nb = nbf.v4.new_notebook(); C = []
md = lambda s: C.append(nbf.v4.new_markdown_cell(s)); code = lambda s: C.append(nbf.v4.new_code_cell(s))

md("# Walking UMA's manifold to a stabler green-hydrogen catalyst\nStandalone Colab version. Use a GPU runtime (Runtime → Change runtime type → T4).")
md("## 0. Setup\nYou need a free Hugging Face account with access to `facebook/UMA` (accept the licence on the model page, then create a read token).")
code("!pip install -q fairchem-core pymatgen scikit-learn")
code("from huggingface_hub import login; login()    # paste your Hugging Face token")
code(f"import urllib.request\nfor f in ['ruo2_110_slab.json', 'landscape_RuO2.json']:\n    urllib.request.urlretrieve('{RAW}data/' + f, f)")
md("## 1. The method, in one cell\n`VirtualUMA` lets any atom carry any element vector. `Chart` is the continuous periodic table. `walk` is gradient ascent on it.")
code(LIB)
code("import numpy as np, json, matplotlib.pyplot as plt\nfrom ase import Atoms\nfrom ase.data import atomic_numbers, chemical_symbols")
md("## 2. Load the model")
code("U = VirtualUMA('cuda')      # downloads uma-s-1p2 (~1 GB) on first use")
md("## 3. Open it up: where do elements live?\nEach element is a row of 128 learned numbers in four lookup tables.")
code("U.W.keys(), U.W['src'].shape")
code("W = {k: U.W[k].cpu().numpy() for k in TABLES}\nW['src'][atomic_numbers['Fe']][:8]         # iron, first 8 of 128 numbers")
md("Nearest neighbours in that space are chemical neighbours.")
code("def nearest(sym, table='src', n=4):\n    X = W[table][1:84]; v = W[table][atomic_numbers[sym]]\n    d = np.linalg.norm(X - v, axis=1); d[atomic_numbers[sym]-1] = np.inf\n    return [chemical_symbols[i+1] for i in np.argsort(d)[:n]]\nfor s in ['Fe', 'Au', 'Cl', 'Na', 'Ti']: print(s, '->', nearest(s))")
md("## 4. The static periodic table, as UMA drew it")
code("from sklearn.decomposition import PCA\nZs = [z for z in range(3, 84) if not 58 <= z <= 71]\nX = np.concatenate([W['src'][Zs], W['tgt'][Zs]], 1)\nP = PCA(3).fit(X); S = P.transform(X); P.explained_variance_ratio_.round(2)")
code("from pymatgen.core.periodic_table import Element\nblock = [Element(chemical_symbols[z]).block for z in Zs]\ncol = {'s': '#E07B39', 'p': '#3B9AB2', 'd': '#6C4AB6', 'f': 'grey'}\nplt.figure(figsize=(9, 6), facecolor='#FAF6EE')\nplt.scatter(S[:, 0], S[:, 1], c=[col[b] for b in block], s=60)\nfor (x, y), z in zip(S[:, :2], Zs): plt.annotate(chemical_symbols[z], (x, y), fontsize=8)\nplt.xlabel('learned axis 1 (~row / size)'); plt.ylabel('learned axis 2 (~electronegativity / group)'); plt.title(\"UMA's periodic table\");")
md("Three learned axes carry most of the table, and they name to row, size and electronegativity. The model rediscovered Mendeleev from energies alone.")
md("## 5. Making element identity continuous\nFirst check: a real vector reproduces the real energy.")
code("U.prime('omat')\nmgo = Atoms('MgO', positions=[[0, 0, 0], [2.1, 0, 0]], cell=[8, 8, 8], pbc=True)\nE_mg = U.energy(mgo)\ncao = mgo.copy(); cao.numbers[0] = atomic_numbers['Ca']; E_ca = U.energy(cao)")
code("V = U.default_V(mgo); set_sites(V, [0], element_vectors(U.W, 'Ca'))\nE_virtual = U.energy(mgo, V)\nprint(f'real Ca {E_ca:.4f}   virtual Ca {E_virtual:.4f}')")
md("Now a point *between* Mg and Ca. It has an energy. It is not a real element, and not a physical mixture either. What matters is the slope.")
code("half = {k: 0.5 * (U.W[k][12] + U.W[k][20]) for k in TABLES}\nV = U.default_V(mgo); set_sites(V, [0], half); print('halfway Mg->Ca:', round(U.energy(mgo, V), 4), ' linear average:', round(0.5 * (E_mg + E_ca), 4))")
md("## 6. The continuous periodic table (the chart)\nA smooth surface through the real elements in (group, period) coordinates.")
code("CH = Chart(U.W)\nCH.coords('Ru'), CH.nearest(5.5, 6.0)")
code("v = CH.vectors(5.5, 6.0)      # a point between Ta and W\n{k: v[k][:3].round(3) for k in v}")
md("## 7. The problem: green hydrogen needs a cheaper anode\nPEM electrolysers use IrO₂ because RuO₂, cheaper and more active, dissolves in acid. It dissolves when its lattice oxygen next to a Ru site gets pulled into the reaction. Dopants that make that oxygen harder to remove are the field's fix (Ta, W, Nb, Ti... found one at a time over a decade).")
md("Load a RuO₂(110) surface. `i` is the most exposed Ru; `nbrs` are the Ru positions a dopant could occupy; `O3` are the three oxygens bonded to the site.")
code("d = json.load(open('ruo2_110_slab.json'))\nslab = Atoms(numbers=d['numbers'], positions=d['positions'], cell=d['cell'], pbc=True)\ni, nbrs = d['i'], d['nbrs']\nzz = slab.positions[:, 2]; dist = slab.get_distances(i, range(len(slab)), mic=True)\nO3 = [int(k) for k in np.argsort(dist) if slab.numbers[k] == 8 and zz[k] > zz.mean() - 1 and dist[k] < 2.6][:3]\nslab.get_chemical_formula(), i, nbrs, O3")
md("## 8. The objective: how tightly is the lattice oxygen held?\nMean energy to remove each of the three oxygens bonded to the site. Higher = more protected.")
code("U.prime('oc22')\ndef protection(V=None):\n    E = U.energy(slab, V); vals = []\n    for k in O3:\n        s = slab.copy(); del s[k]\n        vals.append(U.energy(s, None if V is None else delete_rows(V, [k])) - E)\n    return float(np.mean(vals))\nbase = protection(); base")
md("## 9. One dopant, the old way: substitute and recompute")
code("j = 22\ndef exact(sym):\n    s = slab.copy(); s.numbers[j] = atomic_numbers[sym]\n    E = U.energy(s); vals = []\n    for k in O3:\n        t = s.copy(); del t[k]; vals.append(U.energy(t) - E)\n    return float(np.mean(vals)) - base\nprint('Ta', round(exact('Ta'), 3), '  Cu', round(exact('Cu'), 3))")
md("## 10. The alchemical gradient: which way is uphill?")
code("def f(g, p):\n    V = U.default_V(slab); set_sites(V, [j], CH.vectors(g, p)); return protection(V) - base\ng0, p0 = CH.coords('Ru'); h = 0.25\nslope = ((f(g0 + h, p0) - f(g0 - h, p0)) / (2 * h), (f(g0, p0 + h) - f(g0, p0 - h)) / (2 * h))\nslope")
md("Negative in group, positive in period: fewer d-electrons, heavier row. That is the field's 'high-valence dopant' rule, as a derivative.")
md("## 11. The landscape\nThe objective over the whole continuous table (~20 min on a GPU; a cached copy is loaded by default).")
code("RECOMPUTE = False\nif RECOMPUTE:\n    grid = {(g, p): f(g, p) for g in np.arange(2, 14.01, 0.5) for p in np.arange(4, 6.01, 0.5)}\nelse:\n    L = json.load(open('landscape_RuO2.json')); grid = {tuple(float(x) for x in k.split(',')): v for k, v in L['grid'].items()}\nlen(grid)")
code("gs = sorted({g for g, _ in grid}); ps = sorted({p for _, p in grid}); Z = np.array([[grid[(g, p)] for g in gs] for p in ps])\nplt.figure(figsize=(11, 3.5), facecolor='#FAF6EE'); plt.imshow(Z, origin='lower', extent=[2, 14, 4, 6], aspect='auto', cmap='turbo')\nplt.colorbar(label='lattice-O protection (eV)'); plt.xlabel('group'); plt.ylabel('period')\nfor s in ['Ti', 'V', 'Cr', 'Mn', 'Fe', 'Co', 'Ni', 'Cu', 'Zn', 'Nb', 'Mo', 'Ru', 'Rh', 'Pd', 'Ag', 'Ta', 'W', 'Re', 'Ir', 'Pt', 'Au']:\n    g, p = CH.coords(s); plt.plot(g, p, 'k.'); plt.annotate(s, (g, p), color='w', fontsize=8)\nplt.title('one ridge along groups 5-6, rising toward period 6');")
md("## 12. The walk\nGradient ascent on the chart, starting from Ru.")
code("path = walk(f, 'Ru', CH, steps=8)")
code("g_end, p_end = path[-1]; CH.nearest(g_end, p_end)")
md("## 13. Snap to a real element and confirm")
code("print('Ta', round(exact('Ta'), 3), ' W', round(exact('W'), 3))")
code("CANDS = 'Mg Ca Sr Ba Al Ga In Sn Sb Bi Sc Y La Ti Zr Hf V Nb Ta Cr Mo W Mn Fe Co Ni Cu Zn Rh Pd Ir Pt Ag Au Ge Si'.split()\nranking = sorted(((exact(s), s) for s in CANDS), reverse=True)\nranking[:6], ranking[-4:]")
md("## 14. What the literature says\nTa- and W-doped RuO₂ are established acid-OER stabilisers: Sr/Ta co-doped RuO₂ at 166 mV (Nat. Commun. 2025), Ta/B–RuO₂ (Nat. Commun. 2025), W-doped RuO₂ (multiple reports, 2024–25). The walk recovered them from the model's own geometry, with no chemistry supplied.")
md("## 15. Going further\n* Second derivatives along the manifold predict *all* substitutions from one structure (445 sites: ionic 0.16→0.63, O 0.72→0.90).\n* Cross-site curvature predicts co-doping pairs (0.97 on 45 exact checks; Ta/W doubles the best single dopant).\n* The same derivative at the oxygen site points to fluorine, the experimentally proven anion dopant.")
md(f"![walk]({RAW}media/manifold_walk.gif)")
nb["cells"] = C
nb.metadata["kernelspec"] = {"name": "python3", "display_name": "Python 3", "language": "python"}
nb.metadata["accelerator"] = "GPU"
nbf.write(nb, "walkthrough_colab.ipynb"); print("wrote walkthrough_colab.ipynb with", len(C), "cells")
